services:
  mongodb:
    image: mongo:7
    container_name: sql-nosql-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: starci_admin
      MONGO_INITDB_ROOT_PASSWORD: starci_password
      MONGO_INITDB_DATABASE: starci_nosql_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_sql_nosql:/data/db

volumes:
  mongo_data_sql_nosql:

# Run command:
# docker compose -f .docker/mongodb.yaml up --build -d
