services:
  postgres:
    image: postgres:16
    container_name: sql-nosql-postgres
    environment:
      POSTGRES_USER: starci_user
      POSTGRES_PASSWORD: starci_password
      POSTGRES_DB: starci_sql_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data_sql_nosql:/var/lib/postgresql/data

volumes:
  pg_data_sql_nosql:

# Run command:
# docker compose -f .docker/postgresql.yaml up --build -d
