version: '3.8'

services:
  # Primary Database (EN: Primary Database)
  postgres:
    image: postgres:15-alpine
    container_name: starci-postgres-cache
    environment:
      POSTGRES_USER: starci_user
      POSTGRES_PASSWORD: starci_password
      POSTGRES_DB: starci_db
    ports:
      - '5432:5432'
    restart: always

volumes:
  postgres_data:

# Run command:
# docker compose -f .docker/postgresql.yaml up --build -d
